### ISSUE TITLE
[Bug] Import error on startup, fresh installation

### ISSUE THREAD

**Issue by jaibhavaya** [qmk/qmk_distro_msys#95]
### Describe the Bug

After installing fresh, I open the app and I get this error:

Traceback (most recent call last):                                                                        
  File "C:/QMK_MSYS/mingw64/lib/python3.9/site-packages/qmk_cli/script_qmk.py", line 76, in main          
    import qmk.cli  # noqa                                                                                
  File "C:/Users/jakel/qmk_firmware/lib/python/qmk/cli/__init__.py", line 13, in <module>                 
    from . import doctor                                                                                  
  File "C:/Users/jakel/qmk_firmware/lib/python/qmk/cli/doctor.py", line 12, in <module>                   
    from qmk.questions import yesno                                                                       
  File "C:/Users/jakel/qmk_firmware/lib/python/qmk/questions.py", line 4, in <module>                     
    from milc import cli, format_ansi                                                                     
ImportError: cannot import name 'format_ansi' from 'milc' (C:/QMK_MSYS/mingw64/lib/python3.9/site-packages
/milc/__init__.py)                                                                                        
                                                                                

Same error when I ultimately try running qmk setup as well.

**Comment by zvecr** [comment]
qmk/qmk_firmware#12455

**Comment by jaibhavaya** [comment]
@zvecr so that talks about it being out of date, but I'm using the latest version.  Am I missing something?

**Comment by zvecr** [comment]
Your copy of the `qmk_firmware` repo needs updating.
